AddressBookWebUI/Areas/Admin/Components/AdminLeftSideBarMenuViewComponent.cs
using AddressBookBL.InterfacesOfManagers;
using AddressBookEL.AllEnums;
using AddressBookEL.IdentityModels;
using AddressBookWebUI.Areas.Admin.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AddressBookWebUI.Areas.Admin.Components
{
   
    public class AdminLeftSideBarMenuViewComponent:ViewComponent
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IUserAddressManager    _userAddressManager;

        public AdminLeftSideBarMenuViewComponent(UserManager<AppUser> userManager, IUserAddressManager userAddressManager)
        {
            _userManager = userManager;
            _userAddressManager = userAddressManager;
        }

        public IViewComponentResult Invoke()
        {

            //giriş yapmış kullanıcı var mı?
            var username = User.Identity?.Name;
            if (username == null)
            {
                return View(); //burada Default.cshtml çağırır
            }
            var user = _userManager.FindByNameAsync(username).Result;
            if (user == null)
            {
                return View();  //burada Default.cshtml çağırır
            }

            //giriş yapan Admin rolünde midir
            if (!_userManager.IsInRoleAsync(user, Roles.ADMIN.ToString()).Result)
            {
                return View();  //burada Default.cshtml çağırır
            }

            //#region Yontem 1
            //TempData["TotalUserCount"] = _userManager.Users.Count();
            //TempData["TotalAddressCount"] = _userAddressManager.GetAll().Data.Count();
            //return View("AdminLeftMenu", user); //AdminLeftMenu.cshtml 
            //#endregion



            #region Yontem 2
            AdminLeftMenuViewModel model = new AdminLeftMenuViewModel()
            {
                User = user,
                TotalAddressCount = _userAddressManager.GetAll().Data.Count(),
                TotalUserCount = _userManager.Users.Count()
            };
            return View("AdminLeftMenu2", model); //AdminLeftMenu.cshtml  
            #endregion
        }
    }
}

AddressBookWebUI/Areas/Admin/Components/AdminTopNavMenuViewComponent.cs
using AddressBookEL.AllEnums;
using AddressBookEL.IdentityModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AddressBookWebUI.Areas.Admin.Components
{
    public class AdminTopNavMenuViewComponent : ViewComponent
    {
        private readonly UserManager<AppUser> _userManager;

        public AdminTopNavMenuViewComponent(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public IViewComponentResult Invoke()
        {
            try
            {
                //giriş yapmış kullanıcı var mı?
                var username = User.Identity?.Name;
                if (username==null)
                {
                    return View(new AppUser());
                }
                var user = _userManager.FindByNameAsync(username).Result;
                if (user == null) 
                {
                    return View(new AppUser());
                }

                //giriş yapan Admin rolünde midir
                if(!_userManager.IsInRoleAsync(user, Roles.ADMIN.ToString()).Result)
                {
                    return View(new AppUser());
                }

                return View(user); // Default.cshtml
                               
            }
            catch (Exception ex)
            {
                // ex loglansın
                return View(new AppUser()); // Default.cshtml
            }
        }
    }
}

AddressBookWebUI/Areas/Admin/Views/Shared/AccessDenied.cshtml
@model string?
@{
    ViewData["Title"] = "AccessDenied";
    Layout = "~/Views/Shared/_LayoutFurniAccount.cshtml";
}


<div class="row">
    <div class="col-md-12 text-center pt-5">
        <span class="display-3 thankyou-icon text-primary">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z" />
                <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
            </svg>
        </span>
        <h2 class="display-3 text-black">Dikkat!</h2>
        <p class="lead mb-5">@Model</p>
        <p><a href="/Home/Index" class="btn btn-sm btn-outline-black">Ana Sayfaya Dön</a></p>
    </div>
</div>

AddressBookWebUI/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Kaiadmin - Bootstrap 5 Admin Dashboard</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
          name="viewport" />
    <link rel="icon"
          href="~/admintheme/assets/img/kaiadmin/favicon.ico"
          type="image/x-icon" />



    <!-- Fonts and icons -->
    <script src="~/admintheme/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { families: ["Public Sans:300,400,500,600,700"] },
            custom: {
                families: [
                    "Font Awesome 5 Solid",
                    "Font Awesome 5 Regular",
                    "Font Awesome 5 Brands",
                    "simple-line-icons",
                ],
                urls: ["/admintheme/assets/css/fonts.min.css"],
            },
            active: function () {
                sessionStorage.fonts = true;
            },
        });
    </script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="~/admintheme/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/admintheme/assets/css/plugins.min.css" />
    <link rel="stylesheet" href="~/admintheme/assets/css/kaiadmin.min.css" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="~/admintheme/assets/css/demo.css" />
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar -->
        @await Component.InvokeAsync("AdminLeftSideBarMenu")
        <!-- End Sidebar -->

        <div class="main-panel">
            <div class="main-header">
                <div class="main-header-logo">
                    <!-- Logo Header -->
                    <div class="logo-header" data-background-color="dark">
                        <a href="index.html" class="logo">
                            <img src="~/admintheme/assets/img/kaiadmin/logo_light.svg"
                                 alt="navbar brand"
                                 class="navbar-brand"
                                 height="20" />
                        </a>
                        <div class="nav-toggle">
                            <button class="btn btn-toggle toggle-sidebar">
                                <i class="gg-menu-right"></i>
                            </button>
                            <button class="btn btn-toggle sidenav-toggler">
                                <i class="gg-menu-left"></i>
                            </button>
                        </div>
                        <button class="topbar-toggler more">
                            <i class="gg-more-vertical-alt"></i>
                        </button>
                    </div>
                    <!-- End Logo Header -->
                </div>
                <!-- Navbar Header -->
                @await Component.InvokeAsync("AdminTopNavMenu")
            <!-- End Navbar -->
        </div>

        <div class="container">
            <div class="page-inner">

                    @RenderBody()


            </div>

        </div>

        <footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
                <nav class="pull-left">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="http://www.themekita.com">
                                ThemeKita
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"> Help </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"> Licenses </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                    2024, made with <i class="fa fa-heart heart text-danger"></i> by
                    <a href="http://www.themekita.com">ThemeKita</a>
                </div>
                <div>
                    Distributed by
                    <a target="_blank" href="https://themewagon.com/">ThemeWagon</a>.
                </div>
            </div>
        </footer>
    </div>

    <!-- Custom template | don't include it in your project! -->
    <div class="custom-template">
        <div class="title">Settings</div>
        <div class="custom-content">
            <div class="switcher">
                <div class="switch-block">
                    <h4>Logo Header</h4>
                    <div class="btnSwitch">
                        <button type="button"
                                class="selected changeLogoHeaderColor"
                                data-color="dark"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="blue"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="purple"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="light-blue"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="green"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="orange"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="red"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="white"></button>
                        <br />
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="dark2"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="blue2"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="purple2"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="light-blue2"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="green2"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="orange2"></button>
                        <button type="button"
                                class="changeLogoHeaderColor"
                                data-color="red2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Navbar Header</h4>
                    <div class="btnSwitch">
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="dark"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="blue"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="purple"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="light-blue"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="green"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="orange"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="red"></button>
                        <button type="button"
                                class="selected changeTopBarColor"
                                data-color="white"></button>
                        <br />
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="dark2"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="blue2"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="purple2"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="light-blue2"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="green2"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="orange2"></button>
                        <button type="button"
                                class="changeTopBarColor"
                                data-color="red2"></button>
                    </div>
                </div>
                <div class="switch-block">
                    <h4>Sidebar</h4>
                    <div class="btnSwitch">
                        <button type="button"
                                class="changeSideBarColor"
                                data-color="white"></button>
                        <button type="button"
                                class="selected changeSideBarColor"
                                data-color="dark"></button>
                        <button type="button"
                                class="changeSideBarColor"
                                data-color="dark2"></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="custom-toggle">
            <i class="icon-settings"></i>
        </div>
    </div>
    <!-- End Custom template -->
    </div>
    <!--   Core JS Files   -->
    <script src="~/admintheme/assets/js/core/jquery-3.7.1.min.js"></script>
    <script src="~/admintheme/assets/js/core/popper.min.js"></script>
    <script src="~/admintheme/assets/js/core/bootstrap.min.js"></script>

    <!-- jQuery Scrollbar -->
    <script src="~/admintheme/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

    <!-- Chart JS -->
    <script src="~/admintheme/assets/js/plugin/chart.js/chart.min.js"></script>

    <!-- jQuery Sparkline -->
    <script src="~/admintheme/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

    <!-- Chart Circle -->
    <script src="~/admintheme/assets/js/plugin/chart-circle/circles.min.js"></script>

    <!-- Datatables -->
    <script src="~/admintheme/assets/js/plugin/datatables/datatables.min.js"></script>

    <!-- Bootstrap Notify -->
    <script src="~/admintheme/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

    <!-- jQuery Vector Maps -->
    <script src="~/admintheme/assets/js/plugin/jsvectormap/jsvectormap.min.js"></script>
    <script src="~/admintheme/assets/js/plugin/jsvectormap/world.js"></script>

    <!-- Sweet Alert -->
    <script src="~/admintheme/assets/js/plugin/sweetalert/sweetalert.min.js"></script>

    <!-- Kaiadmin JS -->
    <script src="~/admintheme/assets/js/kaiadmin.min.js"></script>

    <!-- Kaiadmin DEMO methods, don't include it in your project! -->
    <script src="~/admintheme/assets/js/setting-demo.js"></script>
@*     <script src="~/admintheme/assets/js/demo.js"></script>
 *@

    @RenderSection("scriptler", required: false)


</body>
</html>